### DISCUSSION TITLE
Roadmap

### DISCUSSION THREAD

**Discussion by son-link** [son-link/bestodon#1] [Ideas]
- [ ]  Add new lists
  - [ ]  Blogs and websites about Linux, be it news, tutorials and/or games 
- [ ] Improve listings, adding fields for labels and account language
  - [x] Perfomance makedata.js
- [ ] Add I18n support
- [x] Add search

**Comment by son-link** [comment]
Example of the new format for _lists/ files on YAML format:
```yaml
- acct: GIMP@floss.social
  langs:
    - en
  tags:
    - image
    - image_editor

- acct: fdroidorg@floss.social
  langs:
    - en
  tags:
    - android
    - shop
```
